### ISSUE TITLE
fix: color parsing and rendering

### ISSUE THREAD

**Issue by mariz-ov** [pixelaw/p_war_client#19]
- should be 0x12345678 => 12 = R, 34 = G, 56 = B, 78 = Alpha
- add trailing FF for the alpha channel

**Comment by mariz-ov** [comment]
there's an issue with coloring the pixels...there's no trailing FF in the INITIAL_COLOR in p_war when you create a game

**Comment by 0xshora** [comment]
Currently we add trailing 00 for the alpha channel.
