### ISSUE TITLE
fix: activate button

### ISSUE THREAD

**Issue by 0xshora** [pixelaw/p_war_client#28]
Change it to `Activated` or smth after the proposal is activated.

**Comment by 0xshora** [comment]
Button text should be like this:
- Vote: for the acitve proposal.
- Denied: for the closed proposal which is denied.
- Activate: for the closed proposal which is approved and to be activated.
- Applied: for the closed proposal which is approved and activated.

**Comment by mariz-ov** [comment]
@0xshora, there seems to be an issue with the torii graphql. Even though the proposal now has the is_activated field. torii graphql doesn't recognize it.

**Comment by 0xshora** [comment]
the current version is fixed: the graphql recognize it.
<img width="1440" alt="Screenshot 2024-07-02 at 21 25 03" src="https://github.com/pixelaw/p_war_client/assets/44103856/a64a3047-322a-4e35-8088-4ff1a1a885d0">
