### ISSUE TITLE
fix: torii error.

### ISSUE THREAD

**Issue by 0xshora** [pixelaw/p_war_client#33]
![image](https://github.com/pixelaw/p_war_client/assets/44103856/8106cca8-7530-46a3-9bd7-93483f52cc7f)

To reproduce:
- Create a new proposal: add a new color.
- Vote for it with 1PX.
- Activate it.
- play with it.
- Reload the window.

**Comment by mariz-ov** [comment]
the issue was caused by a delete! in the old contract.

changed contract to remove the delete! macro. could not change the storage on p_war though, so to update the changes locally, you'll have to run the initialize script as stated in the README.md
