### ISSUE TITLE
feat: dynamic color palette.

### ISSUE THREAD

**Issue by 0xshora** [pixelaw/p_war_client#34]
If we add a new color, we have to update the color palette.

FYI"
- We have next_color_idx_to_change for Game Model.
- the color at next_color_idx_to_change should be placed in right end with 'old' strings.
- the newest color should be placed in left end with 'new' strings.
- the order should be kept.

**Comment by mariz-ov** [comment]
i'm done with this but it's not reactive for some reason and needs a refresh.
