### ISSUE TITLE
fix: created instance when we do docker compose up -d

### ISSUE THREAD

**Issue by 0xshora** [pixelaw/p_war_client#67]
Did this commands:
- `docker compose down -v`
- `docker compose up -d`

However, there was a grid already when we visit the page before we create a instance.
It's only for the server.
<img width="1440" alt="Screenshot 2024-07-05 at 23 37 11" src="https://github.com/pixelaw/p_war_client/assets/44103856/8ec6c37f-ae83-4d20-bfc6-fced9fddc9e7">

**Comment by mariz-ov** [comment]
I think it's been resolved...don't see the issue anymore
![image](https://github.com/pixelaw/p_war_client/assets/93242047/3f8e8ce3-c191-4eb4-89ac-9d241ad73efe)
